services:
  db:
    container_name: pixshare-postgres-db
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres-user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_DB: pixshare_db
      PGDATA: /data/postgres
    logging:
      options:
        max-size: 10m
        max-file: "5"
    secrets:
      - postgres-user
      - postgres-password
    volumes:
      - db_data:/data/postgres
      - ./init/db/postgres:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_DB_PORT}:${POSTGRES_DB_DEFAULT_PORT}
    networks:
      - db_net

  pixshare-api:
    container_name: pixshare-api
    image: projcodehub/pixshare-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:${POSTGRES_DB_DEFAULT_PORT}/pixshare_db
    ports:
      - 8088:8081
    networks:
      - db_net
    depends_on:
      - db

networks:
  db_net:
    driver: bridge

secrets:
  postgres-user:
    environment: POSTGRES_USER
  postgres-password:
    environment: POSTGRES_PASSWORD

volumes:
  db_data: