name: CI - Build Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15.3-alpine
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_TEST_PASSWORD }}
          POSTGRES_DB: pixshare_test_db
          POSTGRES_DB_PORT: ${{ vars.TEST_DB_PORT }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${{ env.POSTGRES_DB_PORT }}:5432
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and run Unit/Integration tests with Maven
        run: mvn -B -ntp verify